-- Re-seed suggested_books from Read-Aloud Books.xlsx
-- 394 books across 4 age groups with genres assigned

DELETE FROM public.suggested_books;

-- Ages 0-3
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('All the World', 'Liz Garton Scanlon', 'Marla Frazee', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Barnyard Dance', 'Sandra Boynton', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Bee-bim Bop', 'Linda Sue Park', 'Ho Baek Lee', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Blah Blah Black Sheep', 'N. D. Wilson', 'Forrest Dickison', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Blue Hat, Green Hat', 'Sandra Boynton', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Boy of Mine', 'Jabari Asim', 'LeUyen Pham', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Brown Bear, Brown Bear, What Do You See?', 'Bill Martin Jr.', 'Eric Carle', 'ages-0-3', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('But Not the Hippopotamus', 'Sandra Boynton', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Carl''s Afternoon in the Park', 'Alexandra Day', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Carl''s Birthday', 'Alexandra Day', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Carl''s Summer Vacation', 'Alexandra Day', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Charlie Needs a Cloak', 'Tomie dePaola', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Cinderella', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Dear Zoo', 'Rod Campbell', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Each Peach, Pear, Plum', 'Allan and Janet Ahlberg', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Elves and the Shoemaker', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Feast for Ten', 'Cathryn Falwell', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Five Little Monkeys Jumping on the Bed', 'Eileen Christelow', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Fox in Socks', 'Dr. Seuss', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Full Moon at the Napping House', 'Don and Audrey Wood', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Giant Jumperee', 'Julian Donaldson', 'Helen Oxenbury', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Girl of Mine', 'Jabari Asim', 'LeUyen Pham', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Go Dog, Go!', 'P.D. Eastman', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Going-to-Bed Book', 'Sandra Boynton', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Good Dog, Carl', 'Alexandra Day', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Goodnight Gorilla', 'Peggy Rathmann', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Goodnight Moon', 'Margaret Wise Brown', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Gossie', 'Olivier Dunrea', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Grouchy Ladybug', 'Eric Carle', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Gruffalo', 'Julian Donaldson', 'Axel Scheffler', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hand, Hand, Fingers, Thumb', 'Al Perkins', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Happy Hippo, Angry Duck', 'Sandra Boynton', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Harold and the Purple Crayon', 'Crockett Johnson', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hello Ninja', 'N. D. Wilson', 'Forrest Dickison', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Henny Penny', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hop on Pop', 'Dr. Seuss', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A House for Hermit Crab', 'Eric Carle', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('How God Made the World', 'Ella Lindvall', 'H. Kent Puckett', 'ages-0-3', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hush! A Thai Lullaby', 'Minfong Ho', 'Holly Meade', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hush, Little Baby', 'Marla Frazee', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('I''m Grumpy', 'Jennifer L. and Matthew Holm', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('I''m Sunny!', 'Jennifer L. and Matthew Holm', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('If You Give a Moose a Muffin', 'Laura Numeroff', 'Felicia Bond', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Jack and the Beanstalk', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Jamberry', 'Bruce Degen', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Kitten''s First Full Moon', 'Kevin Henkes', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Little Mouse, the Red Ripe Strawberry, and the Big Hungry Bear', 'Don and Audrey Wood', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Little Red Hen', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Llama Llama Red Pajama', 'Anna Dewdney', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mary Engelbreit''s Mother Goose', 'Mary Engelbreit', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Monkey and the Crocodile', 'Paul Galdone', NULL, 'ages-0-3', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mr. Brown Can Moo! Can You?', 'Dr. Seuss', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mr. Gumpy''s Motor Car', 'John Burnhingham', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mr. Gumpy''s Outing', 'John Burnhingham', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('My First Mother Goose', 'Tomie dePaola', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('My Very First Mother Goose', 'Iona Opie', 'Rosemary Wells', 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Napping House', 'Don and Audrey Wood', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('One Fish Two Fish Red Fish Blue Fish', 'Dr. Seuss', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('One-Dog Canoe', 'Mary Casanova', 'Ard Hoyt', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('One-Dog Sleigh', 'Mary Casanova', 'Ard Hoyt', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pancakes for Breakfast', 'Tomie dePaola', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pancakes! Pancakes!', 'Eric Carle', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peek-a-Boo', 'Allan and Janet Ahlberg', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peek-a-Moo!', 'Nina Laden', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peek-a-Who?', 'Nina Laden', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peekaboo Morning', 'Rachel Isadora', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pelle''s New Suit', 'Elsa Beskow', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peter''s Chair', 'Ezra Jack Keats', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Quick As a Cricket', 'Don and Audrey Wood', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Read-Aloud Bible Stories', 'Ella Lindvall', 'H. Kent Puckett', 'ages-0-3', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Real Mother Goose', 'Blanche Fisher Wright', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Richard Scarry''s Best Mother Goose Ever', 'Richard Scarry', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Sheep in a Jeep', 'Nancy Shaw', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Snail and the Whale', 'Julia Donaldson', 'Axel Scheffler', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Snowy Day', 'Ezra Jack Keats', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('So Much!', 'Trish Cooke', 'Helen Oxenbury', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Sylvia Long''s Mother Goose', 'Sylvia Long', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ten Little Fingers and Ten Little Toes', 'Mem Fox', 'Helen Oxenbury', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ten, Nine, Eight', 'Molly Bang', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Bears', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Billy Goats Gruff', 'Paul Galdone', NULL, 'ages-0-3', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Little Kittens', 'Paul Galdone', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Little Pigs', 'Paul Galdone', NULL, 'ages-0-3', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tomie dePaola''s Mother Goose', 'Tomie dePaola', NULL, 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Town Mouse and the Country Mouse', 'Paul Galdone', NULL, 'ages-0-3', 'Fable');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Twinkle, Twinkle, Little Star', NULL, 'Iza Trapani', 'ages-0-3', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Very Hungry Caterpillar', 'Eric Carle', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Very Lonely Firefly', 'Eric Carle', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('We''re Going on a Bear Hunt', 'Michael Rosen', 'Helen Oxenbury', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Whistle for Willie', 'Ezra Jack Keats', NULL, 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Whose Knees Are These?', 'Jabari Asim', 'LeUyen Pham', 'ages-0-3', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Whose Toes Are Those?', 'Jabari Asim', 'LeUyen Pham', 'ages-0-3', 'Picture Book');

-- Ages 4-7
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Amazing Grace', 'Mary Hoffman', 'Caroline Binch', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Anansi and the Magic Stick', 'Eric A. Kimmel', 'Janet Stevens', 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Anansi and the Moss-Covered Rock', 'Eric A. Kimmel', 'Janet Stevens', 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Anansi and the Talking Melon', 'Eric A. Kimmel', 'Janet Stevens', 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Anna Hibiscus', 'Atinuke', 'Lauren Tobia', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Art Lesson', 'Tomie dePaola', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('At Night', 'Jonathan Bean', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Bear Called Paddington', 'Michael Bond', 'Peggy Fortnum', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Bears on Hemlock Mountain', 'Alice Dalgliesh', 'Helen Sewell', 'ages-4-7', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Bee Tree', 'Patricia Polacco', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Begin', 'Philip and Erin Ulrich', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Big Anthony: His Story', 'Tomie dePaola', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Big Snow', 'Jonathan Bean', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Blueberries for Sal', 'Robert McCloskey', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Borrowers', 'Mary Norton', NULL, 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Boxes for Katje', 'Candace Fleming', 'Stacey Dressen-McQueen', 'ages-4-7', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Brave Irene', 'William Steig', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Building Our House', 'Jonathan Bean', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Burgess Animal Book for Children', 'Thornton Burgess', NULL, 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Burgess Bird Book for Children', 'Thornton Burgess', NULL, 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Burgess Seashore Book for Children', 'Thornton Burgess', NULL, 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Chair for My Mother', 'Vera B. Williams', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Chicken Soup with Rice: A Book of Months', 'Maurice Sendak', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Circus Ship', 'Chris Van Dusen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Clown of God', 'Tomie dePaola', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Curious Garden', 'Peter Brown', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Daisy Comes Home', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Down to the Sea with Mr. Magee', 'Chris Van Dusen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Dr. De Soto', 'William Steig', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Dragons of Blueland', 'Ruth Stiles Gannett', 'Ruth Christian Gannett', 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Elmer and the Dragon', 'Ruth Stiles Gannett', 'Ruth Christian Gannett', 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Empty Pot', 'Demi', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Gardener', 'Sarah Stewart', 'David Small', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Gingerbread Christmas', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Good Luck Anna Hibiscus', 'Atinuke', 'Lauren Tobia', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Harriet, You''ll Drive Me Wild!', 'Mem Fox', 'Marla Frazee', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Hat', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hattie & Hudson', 'Chris Van Dusen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Haven', 'Philip and Erin Ulrich', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hedgie''s Surprise', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Honey...Honey...Lion!', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hooray for Anna Hibiscus', 'Atinuke', 'Lauren Tobia', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A House Is a House for Me', 'Mary Ann Hoberman', 'Betty Fraser', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('How to Make a Cherry Pie and See the U.S.A.', 'Marjorie Priceman', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('How to Make an Apple Pie and See the World', 'Marjorie Priceman', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('I Want My Hat Back', 'Jon Klassen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('If I Built a Car', 'Chris Van Dusen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Jesus Storybook Bible', 'Sally Lloyd Jones', 'Jago', 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Julia''s House for Lost Creatures', 'Ben Hatke', NULL, 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Keeping Quilt', 'Patricia Polacco', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('King Hugo''s Huge Ego', 'Chris Van Dusen', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Lady of Guadalupe', 'Tomie dePaola', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Last Stop on Market Street', 'Matt De La Peña', 'Christian Robinson', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Leaf Can Be', 'Laura Purdie Salas', 'Violeta Dabija', 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Legend of Old Befana', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Legend of the Poinsettia', 'Tomie dePaola', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Library', 'Sarah Stewart', 'David Small', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Lion & the Mouse', 'Jerry Pinkney', NULL, 'ages-4-7', 'Fable');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little Bear', 'Else Holmelund Minarik', 'Maurice Sendak', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Make Way for Ducklings', 'Robert McCloskey', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mercy Watson to the Rescue', 'Kate DiCamillo', 'Chris Van Dusen', 'ages-4-7', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Miss Rumphius', 'Barbara Cooney', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Mitten', 'Jan Brett', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('More About Paddington', 'Michael Bond', 'Peggy Fortnum', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Morning', 'Philip and Erin Ulrich', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Mouse and the Motorcycle', 'Beverly Cleary', NULL, 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Muncha! Muncha! Muncha!', 'Candace Fleming', 'G. Brian Karas', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('My Father''s Dragon', 'Ruth Stiles Gannett', 'Ruth Christian Gannett', 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Nana Upstairs & Nana Downstairs', 'Tomie dePaola', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Nate the Great', 'Marjorie Sharmat', 'Marc Simont', 'ages-4-7', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Night Before Christmas', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Nobody Likes a Goblin', 'Ben Hatke', NULL, 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Oh No!', 'Candace Fleming', 'Eric Rohmann', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Old Mother West WInd', 'Thornton Burgess', NULL, 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('One Morning in Maine', 'Robert McCloskey', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Owl Moon', 'Jane Yolen', 'John Schoennher', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ox-Cart Man', 'Donald Hall', 'Barbara Cooney', 'ages-4-7', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Paddington Abroad', 'Michael Bond', 'Peggy Fortnum', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Paddington Helps Out', 'Michael Bond', 'Peggy Fortnum', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Paddington Marches On', 'Michael Bond', 'Peggy Fortnum', 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Puss in Boots', 'Jerry Pinkney', NULL, 'ages-4-7', 'Fairy Tale');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Rechenka''s Eggs', 'Patricia Polacco', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Relatives Came', 'Cynthia Rylant', 'Stephen Gammell', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Rock Can Be', 'Laura Purdie Salas', 'Violeta Dabija', 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Roxaboxen', 'Alice McLerran', 'Barbara Cooney', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Sam and Dave Dig a Hole', 'Mac Barnett', 'Jon Klassen', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Seven Silly Eaters', 'Mary Ann Hoberman', 'Marla Frazee', 'ages-4-7', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Somebody Loves You, Mr. Hatch', 'Eileen Spinelli', 'Paul Yalowitz', 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona Meets Her Match', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona Takes a Vacation', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona''s Gift', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona''s Harvest', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona''s Magic Lessons', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Strega Nona: Her Story', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Tales of Olga da Polga', 'Michael Bond', NULL, 'ages-4-7', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('This Is Not My Hat', 'Jon Klassen', NULL, 'ages-4-7', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('This Is my Home, This Is My School', 'Jonathan Bean', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Thornton Burgess Animal Stories', 'Thornton Burgess', NULL, 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Billy Goats Gruff', 'Jerry Pinkney', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Little Kittens', 'Jerry Pinkney', NULL, 'ages-4-7', 'Nursery Rhymes');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Three Snow Bears', 'Jan Brett', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Thundercake', 'Patricia Polacco', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Time of Wonder', 'Robert McCloskey', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tom', 'Tomie dePaola', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tony''s Bread', 'Tomie dePaola', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tops and Bottoms', 'Janet Stevens', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Tortoise and the Hare', 'Jerry Pinkney', NULL, 'ages-4-7', 'Fable');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tumtum and Nutmeg', 'Emily Bearn', NULL, 'ages-4-7', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Turnip', 'Jan Brett', NULL, 'ages-4-7', 'Folklore');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Water Can Be...', 'Laura Purdie Salas', 'Violeta Dabija', 'ages-4-7', 'Nature');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('We Found a Hat', 'Jon Klassen', NULL, 'ages-4-7', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Widewater', 'Philip and Erin Ulrich', NULL, 'ages-4-7', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Wild Christmas Reindeer', 'Jan Brett', NULL, 'ages-4-7', 'Picture Book');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Winnie-the-Pooh', 'A. A. Milne', 'Ernest H. Shepherd', 'ages-4-7', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Wonderful Wizard of Oz', 'L. Frank Baum', NULL, 'ages-4-7', 'Fantasy');

-- Ages 8-12
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('100 Cupboards', 'N. D. Wilson', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Action Bible', 'Doug Mauss (edited)', 'Sergio Cariello', 'ages-8-12', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Adventures of Huckleberry Finn', 'Mark Twain', NULL, 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Angel Knew Papa and the Dog', 'Douglas Kaine McKelvey', NULL, 'ages-8-12', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ballet Shoes', 'Noel Streatfeild', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Bark of the Bog Owl', 'Jonathan Rogers', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Because of Winn-Dixie', 'Kate DiCamillo', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Blue Birds', 'Caroline Starr Rose', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('By the Great Horn Spoon', 'Sid Fleischman', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('By the Shores of Silver Lake', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Caddie Woodlawn', 'Carol Ryrie Brink', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Charlie and the Chocolate Factory', 'Roald Dahl', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Charlotte''s Web', 'E. B. White', 'Garth Williams', 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Cilla Lee-Jenkins: Future Author Extraordinaire', 'Susan Tan', 'Dana Wulfekotte', 'ages-8-12', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Dreamer', 'Pam Muñoz Ryan', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Edge of Extinction: The Ark Plan', 'Laura Martin', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Egermeier''s Bible Story Book', 'Elise Egermeier', 'Clive Uptton', 'ages-8-12', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ember Falls', 'S. D. Smith', 'Zach Franzen', 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ember Rising', 'S. D. Smith', 'Zach Franzen', 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Emmy and the Incredible Shrinking Rat', 'Lynne Jonell', 'Jonathan Bean', 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Esperanza Rising', 'Pam Muñoz Ryan', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Fablehaven', 'Brandon Mull', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Family Under the Bridge', 'Natalie Savage Carlson', 'Garth Williams', 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Farmer Boy', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Finding Winnie: The True Story of the World''s Most Famous Bear', 'Lindsay Mattick', 'Sophie Blackall', 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Five Children and It', 'Edith Nesbit', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Frindle', 'Andrew Clements', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Gone-Away Lake', 'Elizabeth Enright', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Green Ember', 'S. D. Smith', 'Zach Franzen', 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Half Magic', 'Edward Eager', 'N. M. Bodecker', 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Happy Little Family', 'Rebecca Caudill', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Heidi', 'Johanna Spyri', NULL, 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Henry Huggins', 'Beverly Cleary', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Henry and the Chalk Dragon', 'Jennifer Trafton', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Hidden Gallery', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Horse and His Boy', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Interrupted Tale', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Jasper and the Riddle of Riley''s Mine', 'Caroline Starr Rose', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Johnny Tremain', 'Esther Forbes', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Justin Morgan Had a Horse', 'Marguerite Henry', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Knight''s Castle', 'Edward Eager', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Lion, the Witch and the Wardrobe', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little House in the Big Woods', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little House on the Prairie', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little Town on the Prairie', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Locomotive', 'Brian Floca', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Long Winter', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Long-Lost Home', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Magic by the Lake', 'Elizabeth Enright', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Magic or Not?', 'Edward Eager', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Magician''s Nephew, The', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mary Poppins', 'P. L. Travers', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Matilda', 'Roald Dahl', NULL, 'ages-8-12', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Moffats', 'Eleanor Estes', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Moonshot: The Flight of Apollo 11', 'Brian Floca', NULL, 'ages-8-12', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Mrs. Frisby and the Rats of NIMH', 'Robert C. O''Brien', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('My Side of the Mountain', 'Jean Craighead George', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Mysterious Benedict Society', 'Trenton Lee Stewart', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Mysterious Howling', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Number the Stars', 'Lois Lowry', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('On the Banks of Plum Creek', 'Laura Ingalls WIlder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('On to Oregon!', 'Honore Morrow', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Penderwicks', 'Jeanne Birdsall', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Peter Nimble and His Fantastic Eyes', 'Jonathan Auxier', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Poem for Peter, A: The Story of Ezra Jack Keats and the Creation of The Snowy Day', 'Andrea Davis Pinkney', 'Steve Johnson', 'ages-8-12', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Poppy', 'Avi', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Prairie Thief', 'Melissa Wiley', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Prince Caspian', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Railway Children', 'Edith Nesbit', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Ramona the Pest', 'Beverly Cleary', NULL, 'ages-8-12', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Read-Aloud Book of Bible Stories', 'Amy Steedman', NULL, 'ages-8-12', 'Faith');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Redwall', 'Brian Jacques', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Return to Gone-Away', 'Elizabeth Enright', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Right Word, The: Roget and His Thesaurus', 'Jen Bryant', 'Melissa Sweet', 'ages-8-12', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Rise and Fall of Mount Majestic', 'Jennifer Trafton', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Saturdays', 'Elizabeth Enright', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Search for Delicious', 'Natalie Babbitt', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Secret Garden', 'Frances Hodgson Burnett', NULL, 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Secret School', 'Avi', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Secret of the Swamp King', 'Jonathan Rogers', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Seven-Day Magic', 'Edward Eager', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Silver Chair', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Some Writer!: The Story of E. B. White', 'Melissa Sweet', NULL, 'ages-8-12', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Starry River of the SKy', 'Grace Lin', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Stella by Starlight', 'Sharon Draper', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Stuart LIttle', 'E. B. White', 'Garth Williams', 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Surviving the Applewhites', 'Stephanie S. Tolan', NULL, 'ages-8-12', 'Humor');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Swallows and Amazons', 'Arthur Ransome', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Swiss Family Robinson', 'Johann D. Wyss', NULL, 'ages-8-12', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Tale of Desperaux', 'Kate DiCamillo', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('These Happy Golden Years', 'Laura Ingalls Wilder', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Thirteen Clocks', 'James Thurber', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Time Garden', 'Edward Eager', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Trumpet of the Swan', 'E. B. White', NULL, 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Tuck Everlasting', 'Natalie Babbitt', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Understood Betsy', 'Dorothy Canfield Fisher', NULL, 'ages-8-12', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Unmapped Sea', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Unseen Guest', 'Maryrose Wood', NULL, 'ages-8-12', 'Mystery');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Vanderbeekers of 141st Street', 'Karina Yan Glaser', NULL, 'ages-8-12', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Voyage of the Dawn Treader', 'C. S. Lewis', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Way of the Wilderking', 'Jonathan Rogers', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Well-Wishers', 'Edward Eager', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('When the Sea Turned to Silver', 'Grace Lin', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Where the Mountain Meets the Moon', 'Grace Lin', NULL, 'ages-8-12', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Wind in the Willows', 'Kenneth Grahame', NULL, 'ages-8-12', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Wolves of Willoughby Chase', 'Joan Aiken', NULL, 'ages-8-12', 'Historical Fiction');

-- Ages 13+
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Adventures of Tom Sawyer', 'Mark Twain', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('American Plague, An: The True and Terrifying Story of the Yellow Fever Epidemic of 1793', 'Jim Murphy', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Anne of Green Gables', 'Lucy Maud Montgomery', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Banner in the Sky', 'James Ramsey Ullman', NULL, 'ages-13-plus', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Boundless', 'Kenneth Oppel', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Boys in the Boat', 'Daniel James Brown', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Bridge to Terabithia', 'Katherine Paterson', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Brown Girl Dreaming', 'Jacqueline Woodson', NULL, 'ages-13-plus', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Bud, Not Buddy', 'Christopher Paul Curtis', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Butterfly', 'Patricia Polacco', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Castle', 'David Macaulay', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Cathedral', 'David Macaulay', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Charlatan''s Boy, The', 'Jonathan Rogers', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Christmas Carol', 'Charles Dickens', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('City', 'David Macaulay', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Crossover', 'Kwame Alexander', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Echo', 'Pam Muñoz Ryan', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Enna Burning', 'Shannon Hale', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Fall of Marigolds', 'Susan Meissner', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Fellowship of the Ring', 'J. R. R. Tolkien', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Fever', 'Laurie Halse Anderson', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Forest Born', 'Shannon Hale', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Gathering Blue', 'Lois Lowry', NULL, 'ages-13-plus', 'Science Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Giver', 'Lois Lowry', NULL, 'ages-13-plus', 'Science Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('God''s Smuggler', 'Brother Andrew', NULL, 'ages-13-plus', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Goose Girl', 'Shannon Hale', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hattie Big Sky', 'Kirby Larson', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Hattie Ever After', 'Kirby Larson', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Hiding Place', 'Corrie Ten Boom', NULL, 'ages-13-plus', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Hobbit', 'J. R. R. Tolkien', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Homeless Bird', 'Gloria Whelan', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('How to Win Friends and Influence People', 'Dale Carnegie', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Hunger Games', 'Suzanne Collins', NULL, 'ages-13-plus', 'Science Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Inside Out and Back Again', 'Thanhha Lai', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Let the Circle Be Unbroken', 'Mildred Taylor', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Listening for Lions', 'Gloria Whelan', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little Men', 'Louisa May Alcott', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Little Women', 'Louisa May Alcott', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Long Walk to Water', 'Linda Sue Park', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Meet the Austins', 'Madeleine L''Engle', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Messenger', 'Lois Lowry', NULL, 'ages-13-plus', 'Science Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Monster in the Hollows', 'Andrew Peterson', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Moon Over Manifest', 'Clare Vanderpool', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Navigating Early', 'Clare Vanderpool', NULL, 'ages-13-plus', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('North! Or Be Eaten', 'Andrew Peterson', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Okay for Now', 'Gary D. Schmidt', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('On the Edge of the Dark Sea of Darkness', 'Andrew Peterson', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Out of the Dust', 'Karen Hesse', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Perilous Gard', 'Elizabeth Marie Pope', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Piecing Me Together', 'Renée Watson', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pink and Say', 'Patricia Polacco', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pride and Prejudice', 'Jane Austin', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Princess Academy', 'Shannon Hale', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Pyramid', 'David Macaulay', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Red Scarf Girl', 'Ji-li Jiang', NULL, 'ages-13-plus', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Return of the King', 'J. R. R. Tolkien', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('River Secrets', 'Shannon Hale', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Screwtape Letters', 'C. S. Lewis', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Sherwood Ring', 'Elizabeth Marie Pope', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Show Way', 'Jacqueline Woodson', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Single Shard', 'Linda Sue Park', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Sit-In', 'Andrea Pinkney', 'Brian Pinkney', 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Son', 'Lois Lowry', NULL, 'ages-13-plus', 'Science Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('To Kill a Mockingbird', 'Harper Lee', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Treasure Island', 'Robert Louis Stevenson', NULL, 'ages-13-plus', 'Adventure');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The True Confessions of Charlotte Doyle', 'Avi', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Two Towers', 'J. R. R. Tolkien', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Unbroken (The Young Adult Adaptation): An Olympian''s Journey from Airman to Castaway to Captive', 'Laura Hillenbrand', NULL, 'ages-13-plus', 'Biography');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Warden and the Wolf King', 'Andrew Peterson', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Watsons Go to Birmingham, The--1963', 'Christopher Paul Curtis', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Way Things Work Now', 'David Macaulay', NULL, 'ages-13-plus', 'Nonfiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('The Wednesday Wars', 'Gary D. Schmidt', NULL, 'ages-13-plus', 'Historical Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Where the Red Fern Grows', 'Wilson Rawls', NULL, 'ages-13-plus', 'Classic');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Wingfeather Tales', 'Andrew Peterson', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('Wonder', 'R. J. Palacio', NULL, 'ages-13-plus', 'Fiction');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('A Wrinkle in Time', 'Madeleine L''Engle', NULL, 'ages-13-plus', 'Fantasy');
INSERT INTO public.suggested_books (title, author, illustrator, age_group, genre) VALUES ('You Learn by Living: Eleven Keys to a More Fulfilling Life', 'Eleanor Roosevelt', NULL, 'ages-13-plus', 'Nonfiction');
